'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MinecraftEarthTiles_Core.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 	latDir = tile[0:1]
        '''	latNumber = float(tile[1:3])
        '''	longDir = tile[3:4]
        '''	longNumber = float(tile[4:7])
        '''
        '''	if latDir == &quot;N&quot;:
        '''		yMax = latNumber + 1
        '''	elif latDir == &quot;S&quot;:
        '''		yMax = (latNumber - 1) * -1
        '''	else:
        '''		yMax = 0
        '''
        '''	yMin = yMax - ( 1 * TilesPerMap )
        '''
        '''	if longDir == &quot;E&quot;:
        '''		xMin = longNumber
        '''	elif longDir == &quot;W&quot;:
        '''		xMin = longNumber * -1
        '''	else:
        '''		xMax = 0
        '''
        '''	xMax = xMin + ( 1 * TilesPerMap )
        '''
        '''	#create missing folders
        '''	folder = path + &apos;image_exports/&apos;
        '''	if not os.path.exists(folder):
        '''		 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property basescript() As String
            Get
                Return ResourceManager.GetString("basescript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 	latDir = tile[0:1]
        '''	latNumber = float(tile[1:3])
        '''	longDir = tile[3:4]
        '''	longNumber = float(tile[4:7])
        '''
        '''	if latDir == &quot;N&quot;:
        '''		yMax = latNumber + 1
        '''	elif latDir == &quot;S&quot;:
        '''		yMax = (latNumber - 1) * -1
        '''	else:
        '''		yMax = 0
        '''
        '''	yMin = yMax - ( 1 * TilesPerMap )
        '''
        '''	if longDir == &quot;E&quot;:
        '''		xMin = longNumber
        '''	elif longDir == &quot;W&quot;:
        '''		xMin = longNumber * -1
        '''	else:
        '''		xMax = 0
        '''
        '''	xMax = xMin + ( 1 * TilesPerMap )
        '''
        '''	#create missing folders
        '''	folder = path + &apos;image_exports/&apos;
        '''	if not os.path.exists(folder):
        '''		 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property basescript_bathymetry() As String
            Get
                Return ResourceManager.GetString("basescript_bathymetry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 	latDir = tile[0:1]
        '''	latNumber = float(tile[1:3])
        '''	longDir = tile[3:4]
        '''	longNumber = float(tile[4:7])
        '''
        '''	if latDir == &quot;N&quot;:
        '''		yMax = latNumber + 1
        '''	elif latDir == &quot;S&quot;:
        '''		yMax = (latNumber - 1) * -1
        '''	else:
        '''		yMax = 0
        '''
        '''	yMin = yMax - ( 1 * TilesPerMap )
        '''
        '''	if longDir == &quot;E&quot;:
        '''		xMin = longNumber
        '''	elif longDir == &quot;W&quot;:
        '''		xMin = longNumber * -1
        '''	else:
        '''		xMax = 0
        '''
        '''	xMax = xMin + ( 1 * TilesPerMap )
        '''
        '''	#create missing folders
        '''	folder = path + &apos;image_exports/&apos;
        '''	if not os.path.exists(folder):
        '''		 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property basescript_heightmap() As String
            Get
                Return ResourceManager.GetString("basescript_heightmap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 	latDir = tile[0:1]
        '''	latNumber = float(tile[1:3])
        '''	longDir = tile[3:4]
        '''	longNumber = float(tile[4:7])
        '''
        '''	if latDir == &quot;N&quot;:
        '''		yMax = latNumber + 1
        '''	elif latDir == &quot;S&quot;:
        '''		yMax = (latNumber - 1) * -1
        '''	else:
        '''		yMax = 0
        '''
        '''	yMin = yMax - ( 1 * TilesPerMap )
        '''
        '''	if longDir == &quot;E&quot;:
        '''		xMin = longNumber
        '''	elif longDir == &quot;W&quot;:
        '''		xMin = longNumber * -1
        '''	else:
        '''		xMax = 0
        '''
        '''	xMax = xMin + ( 1 * TilesPerMap )
        '''
        '''	#create missing folders
        '''	folder = path + &apos;image_exports/&apos;
        '''	if not os.path.exists(folder):
        '''		 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property basescript_terrain() As String
            Get
                Return ResourceManager.GetString("basescript_terrain", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
